apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fortiweb.fullname" . }}-workers
  labels:
    {{- include "fortiweb-workers.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fortiweb-workers.selectorLabels" . | nindent 6 }}
  # strategy is supposed to ensure 1 single conf server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "fortiweb-workers.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "fortiweb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          env:
          - name: MGR_MODE_ENV
            value: client
          - name: MGR_SVRIP_ENV
            value:  10.40.40.99
          - name: FWB_ADMIN_PASSWORD
            value: "Fortin3t"
        # {{ include "fortiweb.fullname" . }}.cluster.local  (trying dns resolv)
            # this is the Manager Service's Public IP, need input correct value.
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/manager_config_healthy
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
