apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortiweb-persistent-storage-log
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 4Gi