apiVersion: v1
kind: Service
metadata:
  name: {{ include "fortiweb.fullname" . }}
  labels:
    {{- include "fortiweb.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  loadBalancerIP: 10.40.40.99
  ports:
  - name: gui
    port: 8443
    protocol: TCP
    targetPort: 43
  - name: server
    port: 996
    protocol: TCP
    targetPort: 996
  - name: config-sync
    port: 997
    protocol: TCP
    targetPort: 997
  type: LoadBalancer
  selector:
    {{- include "fortiweb.selectorLabels" . | nindent 4 }}
