apiVersion: v1
kind: Service
metadata:
  name: {{ include "fortiweb.fullname" . }}-workers
  labels:
    {{- include "fortiweb-workers.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portssl }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "fortiweb-workers.selectorLabels" . | nindent 4 }}
