apiVersion: v1
kind: Service
metadata:
  name: {{ include "fortiweb.fullname" . }}
  labels:
    {{- include "fortiweb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portssl }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "fortiweb.selectorLabels" . | nindent 4 }}
